modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/0uti/InfoMod/issues"

[[mods]]
modId="infomod"
version="${file.jarVersion}"
displayName="InfoMod"
description='''Shows a spawn overlay and chunk grids.'''
authors="Outi, Stackoverflow, ..."
credits="42"
side="CLIENT"
#updateJSONURL=""
#displayURL=""
#logoFile=""

[[dependencies.infomod]]
    modId="forge"
    mandatory=true
    versionRange="[31.0.14,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.infomod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
